version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data:/data
    env_file:
      - .env
    networks:
      - app_network

  python_service:
    build:
      context: .
    container_name: python_service
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - app_network
    
volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge